<Project>
  <PropertyGroup>
    <BuildInParallel>false</BuildInParallel>
    <TestTfmsInParallel>false</TestTfmsInParallel>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <None Include="$(MSBuildThisFileDirectory)xunit.runner.json"
          Link="xunit.runner.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(MSBuildThisFileDirectory)test.runsettings"
          Link="test.runsettings"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
